### ISSUE TITLE
Data flow: Merge onto existing state or split up store (cluster details and cluster list?)

### ISSUE THREAD

**Issue by oponder** [giantswarm/happa#1034]
Starting a async discussion here instead of in slack :)

I've noticed that the `CLUSTER_LIST_SUCCESS` reducer replaces the `entities.cluster.items` state with what it got from the API. 

That means that if we had any cluster details already loaded, they will be removed.

<img width="381" alt="Screenshot 2020-01-23 at 8 22 56 AM" src="https://user-images.githubusercontent.com/455309/72965700-4d1bc400-3dbd-11ea-89bf-2675101d8756.png">

As a result, it is basically not safe to do a `clustersList` _without_ following it with `clustersDetails` to repopulate the removed fields (like `api_endpoint`)

Currently when we delete a cluster, we do a `clustersList` to just refresh the list of clusters, but the side effect is that we remove all details from other clusters too. 

This results in the `TypeError: Failed to construct 'URL': Invalid URL` on the KeyPairs component.

Currently in the reducer we have:

```
    case types.CLUSTERS_LIST_SUCCESS:
      draft.items = action.clusters;
      draft.v5Clusters = action.v5ClusterIds;

      return;
```

I would change it for something like:

```
    case types.CLUSTERS_LIST_SUCCESS:
      let clusters = {};
      Object.keys(action.clusters).forEach(clusterID => {
        clusters[clusterID] = Object.assign({}, draft.items[clusterID], action.clusters[clusterID])
      })

      draft.items = clusters;
      draft.v5Clusters = action.v5ClusterIds;
```

But does that bring back a pattern we were trying to get rid of?

An alternative to 'augmenting' existing state objects, would be to store the cluster list, and the individual cluster details as separate things. I think that wouldn't be an easy change to make, but would it make things easier to reason about?

ping @ograu @giantswarm/sig-front-end

**Comment by ograu** [comment]
IMO we should probably get rid of that call to `clustersList()` and let react and redux do their job, probably we will have to make some adjustments somewhere, but now that I am reading it, if we just delete that line, the cluster will be removed from the store and as we are working with immutable updates, this should be reflected to all the views:

```javascript
export const batchedClusterDeleteConfirmed = cluster => async dispatch => {
  try {
    dispatch(push(`/organizations/${cluster.owner}`));
    await dispatch(clusterActions.clusterDeleteConfirmed(cluster));
    dispatch(modalActions.modalHide());
    // ensure refreshing of the clusters list
    await dispatch(clusterActions.clustersList({ withLoadingFlags: false }));
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('Error in batchedClusterDeleteConfirmed', err);
  }
};
```

As for state objects/keys, I prefer to have all cluster details under `clusters.items[id]`, this data belongs to clusters IMO. I probably would have stored `status` and `workers` in independent keys under `entities` because of all the nesting, but I think it is ok the way it is now.

**Comment by ograu** [comment]
BTW I would say that I copy/pasted this line without thinking too much about it.

**Comment by oponder** [comment]
Ok cool! Let's get rid of that line, I'll make a PR.

But I do still have a concern that clearing those fields and then repopulating them  is causing some flashing or unnecessary rending possibly? 

We'd also have to keep in mind to do the load details after every clustersList from now on.

**Comment by ograu** [comment]
> But I do still have a concern that clearing those fields and then repopulating them is causing some flashing or unnecessary rending possibly?

Totally legit concern. And here is where loading flags have an important role to play. I have to complete docs explaining this as Adrian asked me to do. From the top of my head. the only places where this can occur is in lists, and I am now finishing a PR that is using loading flags with spinners to solve this.

If there are views where we have some flashing and we don't want to place an spinner as a solution to this flashing, then, yes a solution like the one you propose could be suitable. Or passing cluster object from cluster list to details thunk instead of storing it in the store.

I would say that we should probably keep things simple for now and tackle those issues when they arise.

> We'd also have to keep in mind to do the load details after every clustersList from now on.

Yes. And thanks for raising this potential issue!

**Comment by oponder** [comment]
Ok! Closing
